const players = [
  {
    name: 'John Smith',
    email: 'johnsmith@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 11-11-2002,
  },
  {
    name: 'Jane Doe',
    email: 'janedoe@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 21-11-2004,
  },
  {
    name: 'Alice Brown',
    email: 'alicebrown@example.com',
    password: 'SecurePassword123!',
    position: 'Goalkeeper',
    date_of_birth: 15-6-1999,
  },
  {
    name: 'Robert Johnson',
    email: 'robertjohnson@example.com',
    password: 'SecurePassword123!',
    position: 'Defender',
    date_of_birth: 22-3-2001,
  },
  {
    name: 'Emily Davis',
    email: 'emilydavis@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 12-9-2003,
  },
  {
    name: 'Michael Miller',
    email: 'michaelmiller@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 18-2-2000,
  },
  {
    name: 'Sarah Wilson',
    email: 'sarahwilson@example.com',
    password: 'SecurePassword123!',
    position: 'Defender',
    date_of_birth: 10-5-2005,
  },
  {
    name: 'David Moore',
    email: 'davidmoore@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 19-7-2004,
  },
  {
    name: 'Laura Taylor',
    email: 'laurataylor@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 25-1-2002,
  },
  {
    name: 'James Anderson',
    email: 'jamesanderson@example.com',
    password: 'SecurePassword123!',
    position: 'Goalkeeper',
    date_of_birth: 30-8-2001,
  },
  {
    name: 'Megan Thomas',
    email: 'meganthomas@example.com',
    password: 'SecurePassword123!',
    position: 'Defender',
    date_of_birth: 11-11-2003,
  },
  {
    name: 'Ethan White',
    email: 'ethanwhite@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 3-12-2000,
  },
  {
    name: 'Chloe Harris',
    email: 'chloeharris@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 5-3-1998,
  },
  {
    name: 'Luke Martin',
    email: 'lukemartin@example.com',
    password: 'SecurePassword123!',
    position: 'Defender',
    date_of_birth: 17-6-1999,
  },
  {
    name: 'Grace Lewis',
    email: 'gracelewis@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 9-10-2002,
  },
  {
    name: 'Nathan Scott',
    email: 'nathanscott@example.com',
    password: 'SecurePassword123!',
    position: 'Goalkeeper',
    date_of_birth: 14-1-1997,
  },
  {
    name: 'Sophia Allen',
    email: 'sophiaallen@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 21-4-2003,
  },
  {
    name: 'Ryan Hall',
    email: 'ryanhall@example.com',
    password: 'SecurePassword123!',
    position: 'Midfield',
    date_of_birth: 29-2-2004,
  },
  {
    name: 'Ella Young',
    email: 'ellayoung@example.com',
    password: 'SecurePassword123!',
    position: 'Defender',
    date_of_birth: 13-7-2001,
  },
  {
    name: 'Benjamin King',
    email: 'benjaminking@example.com',
    password: 'SecurePassword123!',
    position: 'Forward',
    date_of_birth: 24-12-2000,
  },
];

export default players;
